name: Sync Localazy
on:
  schedule:
    # At 00:00 on every Monday UTC
    - cron: '0 0 * * 1'

jobs:
  sync-localazy:
    runs-on: ubuntu-latest
    # Skip in forks
    if: github.repository == 'vector-im/element-x-android'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Run Localazy script
        run: ./tools/localazy/downloadStrings.sh --all
      - name: Create Pull Request for Strings
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Sync Strings from Localazy
          title: Sync Strings
          body: |
            - Update Strings from Localazy
          branch: sync-localazy
          base: develop
